### ISSUE TITLE
Needed help on using 'append' function of 'salvattore' in 'wordpress' with 'infinite scroll'

### ISSUE THREAD

**Issue by pknadella** [rnmp/salvattore#163]
I am building my custom theme using '_s' in 'wordpress' and 'Bootstrap 3', and I am successful in integrating 'salvattore' to achieve masonry layout for my 'archive.php'. But I am struck at implementing the 'append' function to achieve infinite-scroll (using the infinite-scroll plugin not the .js script, I guess both are the same)

Already some guys posted an issue regarding this, and I tried every thing they suggested on that thread....but all my efforts failed, may be I am doing something wrong....I am a complete noob in programming world......so posting an issue here hoping that some one would guide me in achieving what I wanted

below is the loop in archive.php, content.php is intact.....I guess this php code is irrelevant to this issue so below I posted the output HTML
```php
<div id="grid" data-columns> //salvattore grid and data colums used here
			<?php while ( have_posts() ) : the_post(); ?>
				<?php
					get_template_part( 'template-parts/content', get_post_format() );
				?>
			<?php endwhile; ?>
</div>
```
the below css is based on a tutsplus article regarding [salvattore and bootstrap] (http://webdesign.tutsplus.com/tutorials/build-a-dynamic-grid-with-salvattore-and-bootstrap-in-10-minutes--cms-20410)
```css
@media screen and (min-width: 1px) and (max-width: 480px){
    #grid[data-columns]::before {
        content: '1 .col-xs-12';
    }
}
@media screen and (min-width: 481px) and (max-width: 767px){
    #grid[data-columns]::before {
        content: '2 .col-xs-6';
    }
}
@media screen and (min-width:768px) and (max-width: 991px){
    #grid[data-columns]::before {
        content: '3 .col-sm-4';
    }
}
@media screen and (min-width:992px) and (max-width: 9999px){
    #grid[data-columns]::before {
        content: '4 .col-md-3';
    }
}
```
output html
```html
<div id="grid" data-columns="4">
<div class="col-md-3">
<article id="post-1792" class="post-1792 post type-post status-publish format-standard has-post-thumbnail hentry category-uncategorized">...</article>
<article id="post-1771" class="post-1771 post type-post status-publish format-standard has-post-thumbnail hentry category-uncategorized">----</article>
</div>
<div class="col-md-3">
.....
</div>
<div class="col-md-3">
.....
</div>
<div class="col-md-3">
.....
</div>
</div>
<div id="infscr-loading" style="display: none;">...</div>
<article id="post-1736" class="post-1736 post type-post status-publish format-standard has-post-thumbnail hentry category-uncategorized">...</article>
<article id="post-1734" class="post-1734 post type-post status-publish format-standard has-post-thumbnail hentry category-uncategorized">...</article>
<article id="post-1732" class="post-1732 post type-post status-publish format-standard has-post-thumbnail hentry category-uncategorized">...</article>
<article id="post-1730" class="post-1730 post type-post status-publish format-standard has-post-thumbnail hentry category-uncategorized">...</article>
<article id="post-1728" class="post-1728 post type-post status-publish format-standard has-post-thumbnail hentry category-uncategorized">...</article>
<article id="post-1" class="post-1 post type-post status-publish format-standard has-post-thumbnail hentry category-uncategorized">...</article>
</div> <!--#grid-->
<nav class="navigation posts-navigation" role="navigation">
<h2 class="screen-reader-text">Posts navigation</h2>
<div class="nav-links">
<div class="nav-previous">
<a href="http://localhost/salv/page/2/">Older posts</a>
</div>
</div>
</nav>
```
for the html/css above what JS to be used to append new elements to the masnory, thanks in advance
