### ISSUE TITLE
A way to hide "3 .cardcol.size-1of3" in webpage if noscript enabled

### ISSUE THREAD

**Issue by tranxuanthang** [rnmp/salvattore#180]
If browsing my webpage using salvattore with NoScript (a firefox extension) enabled, for example, it left a visible "3 .cardcol.size-1of3" on the webpage. Not a big problem, but some time it annoy me.
![3 .cardcol.size-1of3](http://i.imgur.com/oS3yizh.png)

**Comment by MariusRumpf** [comment]
Use something like in the html5boilerplate where you have a `no-js` class. You can then hide the after element for no-js. Be sure to load the script to remove that class before salvattore.

**Comment by efc** [comment]
I just added a `display: none;` to the my masonry containers. For example:

```css
.masonry-container[data-columns]::before {
    content: '3 .masonry-column.masonry-size-1of3';
    display: none;
}
```

The fact that the `::before` is not displayed does not seem to change the effectiveness of the `::before` for Salvattore.
