### ISSUE TITLE
Number of columns depending on container size?

### ISSUE THREAD

**Issue by shur** [rnmp/salvattore#96]
I want to use Salvattore script in plugin which can be placed in any area on site pages, e.g. in central area or left or right side area. Since you never know in which page area the plugin can be used, you cannot use media queries to set the number of columns. I cannot rely on widow size because when I set the number of columns depending on the window size in one page area the script looks good, while in another page area it looks awful. 

That's why I'm forced to rely on parent container size (area size), not window size. To do this I use **Responsive Elements script** (http://kumailht.com/responsive-elements/).
_Responsive elements makes it possible for any element to adapt and respond to the area they occupy._

Salvattore works correctly with predefined CSS class names and media queries, but it fails to work with CSS class names dynamically added by Responsive Elements script.
**Could you help me find the solution to make them work together?**

works:

``` css
.grid[data-columns]::before {
    content: '3 .column.size-1of3';
}
```

doesn't work:

``` css
.lt800[data-columns]::before {
    content: '4 .column.size-1of4';
}
.lt600[data-columns]::before {
    content: '3 .column.size-1of3';
}
```

**Test example:**
http://jsfiddle.net/shur/qEJc2/
